services:
  psql_db:
    image: postgres:16.3
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql16/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - backend

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  db-data:
networks:
  backend:
